### ISSUE TITLE
Decide on the common denominator for a transport API

### ISSUE THREAD

**Issue by daviddias** [libp2p/interface-connection#1]
Remember to take in account:
- have backpressure
- enable half duplex streams (close from one side, but still open for the other)
- support for full duplex
- tests should be performed by passing two streams

**Comment by gaboose** [comment]
I'm wondering if it makes sense for a connection to a _multicast group_ to implement this API.

It does at first glance. Under the hood, members might be connected in a ring, a tree or a random gossip graph, but all the user cares about is incoming broadcasted messages (or stream of data) and to be able to broadcast themselves.

But what about backpressure. Do the topology and routing links adapting to node capacities count? And the other points.

I'm working on a globally topic-addressable pub/sub p2p system and these abstractions, if widely accepted, would really lower the bar for developers to opt for it in their projects.

In any case, it's great what you're doing! This can open a lot of doors.

**Comment by daviddias** [comment]
@Gaboose how is your p2p pubsub endeavour?

**Comment by gaboose** [comment]
Embarassingly paused in mid-development here: https://github.com/Gaboose/go-pubsub

In terms of the [Poldercast paper](https://scholar.google.com/scholar?q=PolderCast%3A+fast%2C+robust%2C+and+scalable+architecture+for+P2P+topic-based+pub%2Fsub&btnG=&hl=lt&as_sdt=0%2C5) I followed, it's 1/3 done. But I spent a lot of time trying to properly structure the supporting code, refactored a lot of it a couple of times. And it already works with a simpler topology, which is connect everyone to everyone and [flood](https://en.wikipedia.org/wiki/Flooding_%28computer_networking%29), heh.

**Comment by daviddias** [comment]
Interesting, I'm working towards a similar strategy for first implementation, but in JS. Have you seen our pubsub repo https://github.com/libp2p/pubsub ? Right now that repo is more focused on the literature review and getting our minds together to nail down on the API

**Comment by daviddias** [comment]
https://github.com/libp2p/interface-transport
