### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by dirkmc** [libp2p/interface-connection#28]
Currently the Connection interface has the following fields and methods:
- getObservedAddrs(callback)
- getPeerInfo(callback)
- setPeerInfo(peerInfo)
- source
- sink

Which of these are required for the streaming (async/await) interface?

**Comment by dirkmc** [comment]
cc @vasco-santos @jacobheun @alanshaw

**Comment by vasco-santos** [comment]
Moving to use async iterators, I am thinking about the following:

`getObservedAddrs()`: Promise<Multiaddr[]>
`getPeerInfo()`: PeerInfo

`source()` => `Iterable`
`sink()` => `function`

`close()` => Promise

I don't remember why we have `setPeerInfo`.  Any idea @jacobheun ?

I am working on a PR for this today

**Comment by jacobheun** [comment]
> I don't remember why we have setPeerInfo.

Right now, a `Connection` can actually be a wrapping of many `Connection` instances, represented as the not very well named `info` property. `setPeerInfo` ensures that the peerInfo is set recursively on all Connection instances. It is typically called after crypto has identified and verified the peer.

`getPeerInfo()` will need to be async. It's overridden when `libp2p-identify` is on and involves async actions. There may be better ways to do this, but without significant refactoring, it will need to stay the same.

> close() => Promise

adding a close method on connections would be very useful for users as a convenience method.

**Comment by jacobheun** [comment]
The new api has been released, closing this.
