### ISSUE TITLE
Should the filter method be part of the API spec?

### ISSUE THREAD

**Issue by JGAntunes** [libp2p/interface-connection#5]
So basically, while looking into lip2p I came to find that some implementations of the `interface-connection` have a method `filter`, used to validate and filter valid multiaddrs for that connection. This is then used at the current libp2p implementations. Should this be a part of the `interface-connection` spec? Or one shouldn't rely upon the existence of such method in every implementation?

**Comment by daviddias** [comment]
I feel you might be confusing with `interface-transport`, no? Filter is just a convenience though, it is not required for the thing to work.

**Comment by JGAntunes** [comment]
Yeah, sorry @diasdavid, had a bunch of repos open and ended up opening the issue in the wrong one... Anyway, you've answered my question, so thanks ;)

**Comment by daviddias** [comment]
no problem, keep questions coming! :D
