### ISSUE TITLE
Duplexify fork causing breakage on node stable

### ISSUE THREAD

**Issue by ghost** [libp2p/interface-connection#6]
I was trying to figure out why js-ipfs CI has been [failing lately](https://travis-ci.org/ipfs/js-ipfs/builds/144805273) and it seems to be coming from `interface-connection` as of `0.1.6`.

I think it's the duplexify fork: https://github.com/libp2p/interface-connection/commit/de465f49864a0ef96541f32339cccac59c96d117

I didn't dig any deeper as to why this is breaking on node stable (6.3.0) but not earlier (even 6.2.2 works fine for me), but hopefully this is enough to be helpful to you.

**Comment by dignifiedquire** [comment]
See https://github.com/mafintosh/duplexify/issues/6 for details, there is already a fixed branch not all repos have been updated though.
